### ISSUE TITLE
Summary.json Dashboard - negative number for connected clients

### ISSUE THREAD

**Issue by PerfectDark99** [sigp/lighthouse-metrics#28]
In the connected clients section I regularly get negative numbers. Often everything is negative except prysm.

Current status:

![connected_clients](https://user-images.githubusercontent.com/58620501/133650069-49959da1-bf45-49c3-bbd3-ee11ed797e4d.PNG)

Either I'm not getting this chart or something is very wrong.

**Comment by paulhauner** [comment]
Thanks for raising this. It's a known issue we're tracking over in https://github.com/sigp/lighthouse/issues/2553.

I'll close this since we're already tracking it :)
